stages:
  - core
  - deploy

core-test:
  stage: core
  image: git.noukakis.ch:5050/operations/docker-images/rust-alpine:latest
  script:
    - cargo test

core-build:
  stage: core
  image: git.noukakis.ch:5050/operations/docker-images/rust-alpine:latest
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/banscreen

deploy:
  stage: deploy
  needs:
    - core-test
    - core-build
  image:
    name: minio/mc
    entrypoint: ['']
  before_script:
    - mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - mc cp target/release/banscreen minio/homelab-distribution/banscreen/