stages:
  - core
  - deploy

core-test:
  stage: core
  image: git.noukakis.ch:5050/operations/docker-images/rust-alpine:1.79.0
  script:
    - cargo test --lib --bins

core-integration-test:
  stage: core
  image: git.noukakis.ch:5050/operations/docker-images/rust-alpine:1.79.0
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - |
      for i in $(seq 1 30)
      do
          docker info && break
          echo "Waiting for docker to start"
          sleep 1s
      done
  script:
    - cargo test --test "*" -- --test-threads=1
  only:
    - main
    - merge_requests

core-build:
  stage: core
  image: git.noukakis.ch:5050/operations/docker-images/rust-alpine:1.79.0
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/borkscreen

deploy:
  stage: deploy
  needs:
    - core-test
    - core-build
  image:
    name: minio/mc
    entrypoint: ['']
  only:
    - tags
  when: on_success
  before_script:
    - mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - mc cp target/release/borkscreen minio/homelab-distribution/borkscreen/